config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_error'

  get '/dashboard' => 'dashboard#show'

  resources :operations, only: %i[index show]

  resources :sessions, only: :create
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  resources :sources do
    resource :headers, only: :edit
    resource :preview, only: :show
    resource :download, only: :show
    resources :exports, only: %i[index show new create destroy]
  end

  get 'terms', to: 'pages#terms'

  resources :trainings, only: :index

  resources :users, only: %i[new create update]
  get '/users/activation/:token', to: 'users/activations#activate',
    as: 'user_activation'

  resources :works, only: %i[index show new create]

  namespace :admin do
    get '', to: 'dashboard#show'
    get 'doc/markdown', to: 'docs#markdown'
    resources :articles
    resources :offers, only: %i[index show edit update]
    resources :operations, only: %i[index show edit update]
    resources :sources, only: %i[index show]
    resources :subscriptions, only: %i[index show edit update]
    resources :users, only: %i[index show edit update]
    resources :works, only: %i[index show]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def show
    @resources = RESOURCES.map { |e| Admin::ModelPresenter.new(e) }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @works      = current_user.works.latest
    @operations = Operation.active
  end
end

app/views/dashboard/show.haml
%h1 Tableau de bord


- if @works.any?
  %h2 Vos dernières utilisations

  = render 'works/list', works: @works


- if @operations.any? && current_user.sources.any?

  %h2 Actions rapides

  %ul
    - @operations.each do |operation|
      %li
        = link_to operation.name, new_work_path(operation_id: operation)


  %h2 État de votre quota

  %p
    %b= number_with_delimiter current_user.current_subscription_usage
    \/
    = number_with_delimiter current_user.current_subscription_quota
    = precede '(' do
      = succeed ')' do
        = current_user.current_subscription_description


- else

  %p
    Votre tableau de bord liste les dernières opérations réalisées, et permet
    de démarrer rapidement vos analyses.
  %p
    Pour démarrer rapidement, merci
    = precede 'd\'' do
      = succeed '.' do
        = link_to 'ajouter un fichier à vos données', new_source_path

  %hr

  %ol.dashboard_directions
    %li
      = link_to new_source_path do
        Connecter mes données
    %li
      = link_to operations_path do
        Enrichir mes données
    %li
      = link_to operations_path do
        Analyser mes données
    %li
      = link_to works_path do
        Exploiter mes données