config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_error'

  get '/dashboard' => 'dashboard#show'

  resources :operations, only: %i[index show]

  resources :sessions, only: :create
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'

  resources :sources do
    resource :headers, only: :edit
    resource :preview, only: :show
    resource :download, only: :show
    resources :exports, only: %i[index show new create destroy]
  end

  get 'terms', to: 'pages#terms'

  resources :trainings, only: :index

  resources :users, only: %i[new create update]
  get '/users/activation/:token', to: 'users/activations#activate',
    as: 'user_activation'

  resources :works, only: %i[index show new create]

  namespace :admin do
    get '', to: 'dashboard#show'
    get 'doc/markdown', to: 'docs#markdown'
    resources :articles
    resources :offers, only: %i[index show edit update]
    resources :operations, only: %i[index show edit update]
    resources :sources, only: %i[index show]
    resources :subscriptions, only: %i[index show edit update]
    resources :users, only: %i[index show edit update]
    resources :works, only: %i[index show]
  end
end

app/models/export.rb
class Export < ActiveRecord::Base
  CHARSETS    = %w[utf-8 iso-8859-15 iso-8859-1].freeze
  SEPARATORS  = {
    ','   =>  'comma',
    ';'   =>  'semicolon',
    "\t"  =>  'tabulation'
  }.freeze

  belongs_to :source

  after_initialize :set_defaults, if: :new_record?

  validates :source,    presence: true
  validates :charset,   inclusion: CHARSETS
  validates :header,    presence: true
  validates :separator, inclusion: SEPARATORS.keys
  validates :file_name, presence: true

  default_scope { order('created_at DESC') }


  def ready?
    !!sha256
  end

  def path
    File.join(Rails.configuration.sources_path, sha256)
  end

  def charsets
    CHARSETS
  end

  def separators
    SEPARATORS
  end

  def separator_description
    separator.inspect.gsub '"', ''
  end

  def set_defaults
    self.charset ||= 'utf-8'

    self.header = true if header.nil?

    self.separator ||= ','

    unless file_name
      self.file_name = source.file_name
      self.file_name += '.csv' unless self.file_name =~ /\.csv\z/
    end
  end
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  before_action :set_source
  before_action :set_export, only: %i[show destroy]

  def index
    @exports = @source.exports
  end

  def show
    send_file @export.path, type: 'text/csv', filename: @export.file_name
  end

  def new
    @export = @source.exports.new
  end

  def create
    @export = @source.exports.new export_params

    if ExportSaver.new(@export).call
      redirect_to source_exports_path @source
    else
      render :new
    end
  end

  def destroy
    ExportDestroyer.new(@export).call
    redirect_to source_exports_path @source
  end


  private

  def set_source
    @source = current_user.sources.find params[:source_id]
  end

  def set_export
    @export = @source.exports.find params[:id]
  end

  def export_params
    params.require(:export)
      .permit %i[source_id header charset separator file_name]
  end
end

app/views/exports/index.haml
%h1
  Export des données
  = "« #{@source.label} »"


- if @exports.any?
  %table.exports-list
    %thead
      %tr
        %th
          Export
        %th
          En-tête
        %th
          Jeu de caractère
        %th
          Séparateur
        %th.list-date
          Exporté le
        %th.list-actions
          Actions

    %tbody
      - @exports.each do |export|
        %tr
          %td
            - if export.ready?
              = link_to export.file_name, source_export_path(@source, export)
            - else
              = export.file_name
          %td.list-boolean
            = export.header? ? 'oui' : 'non'
          %td.list-short-enum
            = export.charset.upcase
          %td.list-short-enum
            = export.separator_description
          %td.list-date
            - if export.ready?
              = l export.updated_at
            - else
              (en cours)
          %td.list-actions
            - if export.ready?
              %ul.actions
                = action_link :delete, [@source, export]

- else
  %p Aucun export disponible.


%ul.actions
  %li
    = link_to 'Nouvel export', new_source_export_path

app/views/exports/new.haml
%h1
  Nouvel export des données
  = "« #{@source.label} »"


= form_for [:source, @export], html: { class: 'form' } do |f|
  %fieldset
    %p.field
      = f.check_box :header
      = f.label :header

    %p.field
      = f.label :charset
      %br
      = f.select :charset, @export.charsets.map { |e| [e.upcase, e] }

    %p.field
      = f.label :separator
      %br
      = f.select :separator,
        @export.separators.map { |k, v| ["#{t v} #{k.inspect}", k] }

    %p.field
      = f.label :file_name
      %br
      = f.text_field :file_name


    - if @export.errors.any?
      .form-errors
        %p= t('errors_count', count: @export.errors.size)
        %ul
          - @export.errors.full_messages.each do |e|
            %li= e


  %ul.actions
    %li
      = f.button 'Exporter'
    %li
      = link_to 'Retour', source_exports_path(@source)